title: Matthew Tyler
position: Postdoctoral Scholar
affiliation: Stanford University
email: mdtyler (at) stanford.edu
keywords: minimal academic
google_scholar: https://scholar.google.com/citations?hl=en&user=QC_IdnMAAAAJ
github_link: https://github.com/matthewtyler
linkedin: 
avatar: ./assets/img/avatar.jpg
google_analytics: 
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: 
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
