title: Matthew Tyler
position: Assistant Professor
affiliation: Rice University
email: mt111 (at) rice.edu
keywords: minimal academic
google_scholar: https://scholar.google.com/citations?hl=en&user=QC_IdnMAAAAJ
github_link:
linkedin: 
avatar: ./assets/img/avatar.jpg
google_analytics: 
favicon: 
favicon_dark: 
description: 
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light